namespace Swarm.Render;

/// <summary>The marker line every generated file carries, so <c>swarm render</c> can tell its own output from hand-written files.</summary>
public static class GeneratedMarker
{
    /// <summary>The marker line in agent files (first body line) and the runbook (first line).</summary>
    public const string MarkdownLine = "<!-- swarm:generated -->";

    /// <summary>The marker line in workflow scripts (the line after the <c>meta</c> line).</summary>
    public const string ScriptLine = "// swarm:generated";

    /// <summary>
    /// True when the marker is where the renderers put it: line 1 (runbook), the line after the front-matter (agent file), or
    /// line 2 after the <c>meta</c> line (workflow script). A marker line anywhere else, such as pasted into a prompt, does not count.
    /// </summary>
    /// <param name="content">The file content.</param>
    /// <returns>Whether the file was generated by <c>swarm render</c>.</returns>
    public static bool IsPresent(string content)
    {
        var lines = content.Split('\n').Select(l => l.TrimEnd('\r')).ToArray();
        string? At(int i) => i < lines.Length ? lines[i] : null;
        if (At(0) == MarkdownLine || At(1) == ScriptLine) return true;
        if (At(0) != "---") return false;
        var close = Array.IndexOf(lines, "---", 1);
        return close > 0 && At(close + 1) == MarkdownLine;
    }
}
