namespace Swarm.Render;

/// <summary>The marker line every generated file carries, so <c>swarm render</c> can tell its own output from hand-written files.</summary>
public static class GeneratedMarker
{
    /// <summary>The marker line in agent files (first body line) and the runbook (first line).</summary>
    public const string MarkdownLine = "<!-- swarm:generated -->";

    /// <summary>The marker line in workflow scripts (the line after the <c>meta</c> line).</summary>
    public const string ScriptLine = "// swarm:generated";

    /// <summary>True when the content has a line that is exactly one of the marker lines (a trailing CR is ignored).</summary>
    /// <param name="content">The file content.</param>
    /// <returns>Whether the file was generated by <c>swarm render</c>.</returns>
    public static bool IsPresent(string content) =>
        content.Split('\n').Select(l => l.TrimEnd('\r')).Any(l => l is MarkdownLine or ScriptLine);
}
