<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Swarm.Tooling.props" />
  <ItemGroup>
    <ProjectReference Include="..\Swarm.Git\Swarm.Git.csproj" />
    <ProjectReference Include="..\Swarm.RunState\Swarm.RunState.csproj" />
    <ProjectReference Include="..\Swarm.Gate\Swarm.Gate.csproj" />
  </ItemGroup>
</Project>
